def reject_nc(nc):
    tol = len(nc)
    num7 = len(nc.select_atoms("prop z > {} and prop z < {}".format(0,20)))
    num6 = len(nc.select_atoms("prop z > {} and prop z < {}".format(20,20+7.21)))
    num5 = len(nc.select_atoms("prop z > {} and prop z < {}".format(20+7.21,20+7.21+gap)))
    num4 = len(nc.select_atoms("prop z > {} and prop z < {}".format(20+7.21+gap, 20+2*7.21+gap)))
    num3 = len(nc.select_atoms("prop z > {} and prop z < {}".format(20+2*7.21+gap, 20+2*7.21+2*gap)))
    num2 = len(nc.select_atoms("prop z > {} and prop z < {}".format(20+2*7.21+2*gap, 20+3*7.21+2*gap)))
    num1 = len(nc.select_atoms("prop z > {} and prop z < {}".format( 20+3*7.21+2*gap, 250)))

    print(num1/tol)
    print(num2/tol)
    print(num3/tol)
    print(num4/tol)
    print(num5/tol)
    print(num6/tol)
    print(num7/tol)